[project]
authors = ["ken <1610057945@qq.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Week1"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[pypi-dependencies]
opencv-python = ">=4.11.0.86, <5"
ultralytics = ">=8.3.91, <9"
torch = ">=2.6.0, <3"

[dependencies]
python = ">=3.13.2,<3.14"
